#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# inventory_tree.sh: Output file/folder trees for key locations
# Usage: bash inventory_tree.sh [--full] [--depth N]
#
# Default: depth 3, skips .git internals and node_modules
# --full:  depth 5, includes hidden dirs (except .git internals)
# --depth N: override depth
#
# Output: ~/inventory_$(date).md
# -----------------------------------------------------------------------------

HOME_DIR="__HOME__"
DEPTH=3
FULL=false

# -- Parse args --
while [[ $# -gt 0 ]]; do
  case "$1" in
    --full)   FULL=true; DEPTH=5; shift ;;
    --depth)  DEPTH="$2"; shift 2 ;;
    *) echo "Unknown arg: $1"; exit 1 ;;
  esac
done

OUT="$HOME_DIR/inventory_$(date +%Y%m%d_%H%M%S).md"

# -- Check tree is available --
if ! command -v tree &>/dev/null; then
  echo "tree not installed. Installing..."
  sudo apt-get install -y tree &>/dev/null || {
    echo "[ERROR] Could not install tree. Run: sudo apt-get install tree"
    exit 1
  }
fi

# -- Exclusions --
# Always skip: .git internals, node_modules, __pycache__, venv site-packages
PRUNE_ALWAYS="--prune -I '__pycache__|node_modules|*.pyc|*.pyo'"
GIT_OPTS="-I '.git'"

if $FULL; then
  # Show hidden dirs (but not .git contents)
  TREE_OPTS="-a --dirsfirst -L $DEPTH --filelimit 200 -I '.git|__pycache__|node_modules|*.pyc'"
else
  TREE_OPTS="--dirsfirst -L $DEPTH --filelimit 100 -I '__pycache__|node_modules|*.pyc|*.pyo'"
fi

# -----------------------------------------------------------------------------
write_section() {
  local label="$1"
  local path="$2"

  echo "" >> "$OUT"
  echo "## $label" >> "$OUT"
  echo "" >> "$OUT"
  echo "\`\`\`" >> "$OUT"

  if [[ ! -d "$path" ]]; then
    echo "(not found: $path)" >> "$OUT"
  else
    # Size summary
    SIZE=$(du -sh "$path" 2>/dev/null | cut -f1)
    COUNT=$(find "$path" -not -path '*/.git/*' -not -path '*/node_modules/*' \
            -not -path '*/__pycache__/*' 2>/dev/null | wc -l)
    echo "$path  [$SIZE | ~$COUNT items]" >> "$OUT"
    echo "" >> "$OUT"
    eval tree $TREE_OPTS "$path" 2>/dev/null >> "$OUT" || \
      find "$path" -maxdepth "$DEPTH" -not -path '*/.git/*' | \
        sed "s|$HOME_DIR/||g" | sort >> "$OUT"
  fi

  echo "\`\`\`" >> "$OUT"
}
# -----------------------------------------------------------------------------

# -- Header --
cat >> "$OUT" << HEADER
# System Inventory: $(date '+%Y-%m-%d %H:%M')
Depth: $DEPTH | Full mode: $FULL
Generated by inventory_tree.sh

---
HEADER

# -- Git repo summary (fast, useful context) --
echo "" >> "$OUT"
echo "## Git Repos Found" >> "$OUT"
echo "" >> "$OUT"
echo "\`\`\`" >> "$OUT"
find "$HOME_DIR/Projects" "$HOME_DIR/Documents" "$HOME_DIR/Desktop" "$HOME_DIR/Archives" \
  -maxdepth 4 -name ".git" -type d 2>/dev/null | while read -r gitdir; do
  repo=$(dirname "$gitdir")
  branch=$(git -C "$repo" branch --show-current 2>/dev/null || echo "?")
  last=$(git -C "$repo" log -1 --format="%h %s" 2>/dev/null || echo "no commits")
  echo "  ${repo#$HOME_DIR/}  [$branch]  $last"
done
echo "\`\`\`" >> "$OUT"

# -- Docker containers --
echo "" >> "$OUT"
echo "## Docker Containers" >> "$OUT"
echo "" >> "$OUT"
echo "\`\`\`" >> "$OUT"
sudo docker ps -a --format "table {{.Names}}\t{{.Status}}\t{{.Image}}" 2>/dev/null \
  >> "$OUT" || echo "(docker not accessible)" >> "$OUT"
echo "\`\`\`" >> "$OUT"

# -- Ollama models --
echo "" >> "$OUT"
echo "## Ollama Models" >> "$OUT"
echo "" >> "$OUT"
echo "\`\`\`" >> "$OUT"
ollama list 2>/dev/null >> "$OUT" || echo "(ollama not running)" >> "$OUT"
echo "\`\`\`" >> "$OUT"

# -- Directory trees --
write_section "Projects"  "$HOME_DIR/Projects"
write_section "Documents" "$HOME_DIR/Documents"
write_section "Downloads" "$HOME_DIR/Downloads"
write_section "Desktop"   "$HOME_DIR/Desktop"
write_section "Archives"  "$HOME_DIR/Archives"

# -- Crontab --
echo "" >> "$OUT"
echo "## Crontab" >> "$OUT"
echo "" >> "$OUT"
echo "\`\`\`" >> "$OUT"
crontab -l 2>/dev/null >> "$OUT" || echo "(no crontab)" >> "$OUT"
echo "\`\`\`" >> "$OUT"

# -- .env keys (names only, no values) --
echo "" >> "$OUT"
echo "## .env Keys (names only)" >> "$OUT"
echo "" >> "$OUT"
echo "\`\`\`" >> "$OUT"
ENV_FILE="$HOME_DIR/Projects/your-stack/.env"
if [[ -f "$ENV_FILE" ]]; then
  grep -v "^#" "$ENV_FILE" | grep "=" | cut -d= -f1 | sed 's/^/  /' >> "$OUT"
else
  echo "(not found: $ENV_FILE)" >> "$OUT"
fi
echo "\`\`\`" >> "$OUT"

# -- Done --
echo "" >> "$OUT"
echo "---" >> "$OUT"
echo "*Generated: $(date) | Script: inventory_tree.sh*" >> "$OUT"

echo ""
echo "Done: $OUT"
echo "Size: $(du -sh "$OUT" | cut -f1)"
echo ""
echo "Upload $OUT to Claude for a full picture."
